version: '3.7'

services:
  news_backend:
    build:
      context: ./backend
    command: sh -c "pip install -r requirements.txt && python3 manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8080 project.wsgi"
    expose:
      - 8080
#    ports:
#      - 80:8080
    volumes:
      - ./backend:/usr/src/news
    environment:
      - DEBUG=False
      - SECRET_KEY=DJANGO_SECRET_KEY
  news_frontend:
    build:
      context: ./frontend
    command: npm run-script build
    volumes:
      - news_build_folder:/frontend/build
    environment:
      - REACT_APP_PRODUCTION_URL=http://127.0.0.1:8001/
  news_nginx:
    build:
      context: ./nginx
    ports:
      - 8001:8080
    volumes:
      - news_build_folder:/var/www/frontend
      - ./backend:/usr/src/news
    depends_on:
      - news_backend
      - news_frontend
volumes:
  news_build_folder: