version: '3.7'

services:
  news_backend:
    build:
      context: ./backend
    command: sh -c "pip install -r requirements.txt && python3 manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8080 project.wsgi"
    expose:
      - 8080
#    ports:
#      - 80:8080
    volumes:
#      - static:./backend/static
      - ./backend:/usr/src/news
  news_frontend:
    build:
      context: ./frontend
    command: npm run-script build
    volumes:
      - news_build_folder:/frontend/build
  news_nginx:
#    image: nginx:latest
    build:
      context: ./nginx
    ports:
      - 80:8080
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - news_build_folder:/var/www/frontend
      - ./backend:/usr/src/news
    depends_on:
      - news_backend
      - news_frontend
volumes:
  news_build_folder: